.idea/.gitignore, android/app/src/main/java/com/goliath/emojihub/RootActivity.kt, android/app/src/main/java/com/goliath/emojihub/views/SignUpPage.kt
=> feat: implement sign up page

.gitmodules
영상->emoji매칭용 X3D 모델 셋업
- X3D모델이 HaGRID 데이터셋을 불러와서 사용할 수 있도록 Dataset, Dataloader 클래스 생성
- HaGRID 데이터셋을 이용해 efficient_x3d_s 모델(pretrained=False)을 학습시키기 위한 스크립트 작성
- ![HaGrid Github](https://github.com/hukenovs/hagrid)에서 **HaGRID 512px** 데이터셋을 다운로드 해 사용함 (original dataset은 750+GB라 해서...)
- 로컬에서 학습을 돌러보았을 때 속도가 더뎌 colab 등 클라우드 환경에서 돌리는 것이 좋을 듯함.
- 클라우드에서 데이터셋 준비한 후 데이터셋 경로 수정하기
- 학습 진행 상황 보며 learning rate, LR scheduler 등 수정하기
-
=> Setup: make HaGRID dataset & train script for x3d,HaGRID

android/app/src/main/java/com/goliath/emojihub/views/LoginPage.kt, android/app/src/main/java/com/goliath/emojihub/views/SignUpPage.kt, android/app/src/main/java/com/goliath/emojihub/views/components/UnderlinedTextField.kt
- wireframe 업데이트된 내용에 맞춰 회원가입 페이지 UI를 수정하였습니다
- 공통적으로 사용되는 밑줄 있는 텍스트필드를 `UnderlinedTextField`로 추출하였습니다
=> Refactor signup page UI

android/app/build.gradle.kts, android/app/src/main/java/com/goliath/emojihub/RootActivity.kt, android/app/src/main/java/com/goliath/emojihub/data_sources/NetworkModule.kt, android/app/src/main/java/com/goliath/emojihub/data_sources/UserApi.kt, android/app/src/main/java/com/goliath/emojihub/models/User.kt, android/app/src/main/java/com/goliath/emojihub/models/responses/LoginResponseDto.kt, android/app/src/main/java/com/goliath/emojihub/repositories/remote/UserRepository.kt, android/app/src/main/java/com/goliath/emojihub/ui/theme/Color.kt, android/app/src/main/java/com/goliath/emojihub/usecases/UserUseCase.kt, android/app/src/main/java/com/goliath/emojihub/viewmodels/UserViewModel.kt, android/app/src/main/java/com/goliath/emojihub/views/FeedPage.kt, android/app/src/main/java/com/goliath/emojihub/views/LoginPage.kt, android/app/src/main/java/com/goliath/emojihub/views/ProfilePage.kt, android/app/src/main/java/com/goliath/emojihub/views/components/EmptyProfile.kt, android/app/src/main/java/com/goliath/emojihub/views/components/ProfileMenuCell.kt
- 프로필 탭의 UI(로그인 상태, 비로그인 상태)를 구현하였습니다
- 로그인 기능을 구현하였고, `UserViewModel`과의 연결을 통해 프로필 탭에서 현재 사용자의 이름을 보여줍니다  (영상 참고)
- 추후 `NavController`과의 연결을 통해 각 cell을 눌렀을 시 다른 페이지로 이동하기의 구현이 필요합니다
https://github.com/snuhcs-course/swpp-2023-project-team-2/assets/70614553/1a0bde9e-2da0-4cb9-b20f-67bce9ca2e01
=> Implement profile tab UI

android/app/src/main/java/com/goliath/emojihub/data_sources/NetworkModule.kt, android/app/src/main/java/com/goliath/emojihub/data_sources/api/EmojiApi.kt, android/app/src/main/java/com/goliath/emojihub/data_sources/api/PostApi.kt, android/app/src/main/java/com/goliath/emojihub/data_sources/api/UserApi.kt, android/app/src/main/java/com/goliath/emojihub/repositories/remote/EmojiRepository.kt, android/app/src/main/java/com/goliath/emojihub/repositories/remote/UserRepository.kt
- api를 별도의 디렉토리에 모아 보관하도록 수정하였습니다
- 조만간 추가될 `AuthInterceptor`를 위한 준비와 네트워크 에러 처리를 위한 준비를 해두었습니다
=> Refact network structure

android/.idea/deploymentTargetDropDown.xml, android/app/src/main/AndroidManifest.xml, android/app/src/main/java/com/goliath/emojihub/NavigationDestination.kt, android/app/src/main/java/com/goliath/emojihub/data_sources/NetworkModule.kt, android/app/src/main/java/com/goliath/emojihub/repositories/RepositoryModule.kt, android/app/src/main/java/com/goliath/emojihub/repositories/remote/PostRepository.kt, android/app/src/main/java/com/goliath/emojihub/usecases/PostUseCase.kt, android/app/src/main/java/com/goliath/emojihub/usecases/UseCaseModule.kt, android/app/src/main/java/com/goliath/emojihub/viewmodels/PostViewModel.kt, android/app/src/main/java/com/goliath/emojihub/views/BottomNavigationBar.kt, android/app/src/main/java/com/goliath/emojihub/views/CreatePostPage.kt, android/app/src/main/java/com/goliath/emojihub/views/FeedPage.kt, android/app/src/main/java/com/goliath/emojihub/views/LoginPage.kt, android/app/src/main/java/com/goliath/emojihub/views/components/TopNavigationBar.kt
- 새 포스트 작성 UI를 구현했습니다
- 포스트 관련 API 연결을 염두하고 `ViewModel`~`DataSource` 셋업을 포함하였습니다
=> Implement creating post UI

android/app/src/main/java/com/goliath/emojihub/usecases/UserUseCase.kt, android/app/src/main/java/com/goliath/emojihub/viewmodels/UserViewModel.kt, android/app/src/main/java/com/goliath/emojihub/views/ProfilePage.kt
- 로그아웃, 회원탈퇴 기능을 간단히 구현하였습니다
- 우선은 서버 API가 마련되지 않아 `currentUser`를 `null`로 만드는 방식으로 우회하였습니다
- 추후 `AlertDialog`를 별도 component로 분리할 예정입니다
=> Implement simple login & signOut

android/app/src/main/java/com/goliath/emojihub/models/Emoji.kt, android/app/src/main/java/com/goliath/emojihub/views/BottomNavigationBar.kt, android/app/src/main/java/com/goliath/emojihub/views/EmojiPage.kt, android/app/src/main/java/com/goliath/emojihub/views/components/EmojiCell.kt
- 새롭게 변경된 디자인에 맞추어 `EmojiCell.kt`를 수정하였습니다
- `EmojiTab`에서 보여줄 `dummyEmoji`를 조금 더 다채롭게 보여줄 `createDummyEmoji()` 함수를 추가했습니다
=> Fix `EmojiCell` UI

android/app/src/main/java/com/goliath/emojihub/EmojiHubApplication.kt, android/app/src/main/java/com/goliath/emojihub/data_sources/NetworkModule.kt, android/app/src/main/java/com/goliath/emojihub/data_sources/SharedLocalStorage.kt, android/app/src/main/java/com/goliath/emojihub/data_sources/api/PostApi.kt, android/app/src/main/java/com/goliath/emojihub/data_sources/api/UserApi.kt, android/app/src/main/java/com/goliath/emojihub/models/Post.kt, android/app/src/main/java/com/goliath/emojihub/repositories/remote/PostRepository.kt, android/app/src/main/java/com/goliath/emojihub/usecases/PostUseCase.kt, android/app/src/main/java/com/goliath/emojihub/usecases/UserUseCase.kt, android/app/src/main/java/com/goliath/emojihub/viewmodels/PostViewModel.kt, android/app/src/main/java/com/goliath/emojihub/views/CreatePostPage.kt, android/app/src/main/java/com/goliath/emojihub/views/EmojiPage.kt
- 게시물 작성을 구현하였습니다
- 로그인 이후 `accessToken`을 `SharedPreference`에 저장하도록 합니다. 이 부분은 나중에 좀 더 깔끔하게 다듬고 싶네요
- 게시물 작성 API 말고도 편집/수정/삭제 관련 API는 연결해두긴 했는데, 지금 앱 UI 상으로는 이 기능들을 제공하고 있지 않아서 포스트 작성까지만 구현하였습니다
=> Upload post to remote server

android/app/src/main/assets/hagrid_classname_to_unicode.json, android/app/src/main/assets/hagrid_id_to_classname.json, android/app/src/main/java/com/goliath/emojihub/repositories/local/X3dRepository.kt
Heuristic Evaluation 시 emoji unicode, default emoji 등의 수정사항 반영
=> fix: fix class unicode info and reformat class files to be readable

android/app/src/main/java/com/goliath/emojihub/NavigationDestination.kt, android/app/src/main/java/com/goliath/emojihub/RootActivity.kt, android/app/src/main/java/com/goliath/emojihub/data_sources/api/EmojiApi.kt, android/app/src/main/java/com/goliath/emojihub/extensions/Extensions.kt, android/app/src/main/java/com/goliath/emojihub/models/Emoji.kt, android/app/src/main/java/com/goliath/emojihub/repositories/remote/EmojiRepository.kt, android/app/src/main/java/com/goliath/emojihub/usecases/EmojiUseCase.kt, android/app/src/main/java/com/goliath/emojihub/viewmodels/EmojiViewModel.kt, android/app/src/main/java/com/goliath/emojihub/views/BottomNavigationBar.kt, android/app/src/main/java/com/goliath/emojihub/views/EmojiPage.kt, android/app/src/main/java/com/goliath/emojihub/views/FeedPage.kt, android/app/src/main/java/com/goliath/emojihub/views/components/EmojiCell.kt, android/app/src/main/java/com/goliath/emojihub/views/components/PlayEmojiView.kt, android/app/src/main/java/com/goliath/emojihub/views/components/TopNavigationBar.kt
- `EmojiCell`을 선택하는 경우 전체 화면으로 이모지를 재생하고, 저장(혹은 삭제)할 수 있습니다
- TODO: API 연결 및 UI 작업만 해두었기에 서버로부터 `dummyEmojiList`를 가져와 실제 동작을 확인해볼 필요가 있습니다
=> Implement saving & playing Emoji

springboot/src/main/kotlin/com/goliath/emojihub/springboot/domain/emoji/controller/EmojiController.kt, springboot/src/main/kotlin/com/goliath/emojihub/springboot/domain/emoji/dto/GetEmojisRequest.kt, springboot/src/main/kotlin/com/goliath/emojihub/springboot/domain/post/controller/PostController.kt, springboot/src/main/kotlin/com/goliath/emojihub/springboot/domain/post/dao/PostDao.kt, springboot/src/main/kotlin/com/goliath/emojihub/springboot/domain/post/dto/GetPostsRequest.kt, springboot/src/main/kotlin/com/goliath/emojihub/springboot/domain/post/service/PostService.kt, springboot/src/main/kotlin/com/goliath/emojihub/springboot/domain/user/dao/UserDao.kt, springboot/src/main/kotlin/com/goliath/emojihub/springboot/domain/user/dto/UserDto.kt, springboot/src/main/kotlin/com/goliath/emojihub/springboot/domain/user/service/UserService.kt
* emoji, post 이 GET API 수정 (RequestBody -> RequestParam)
=> fix: fix RequestBody to RequestParam in GET API

springboot/src/main/kotlin/com/goliath/emojihub/springboot/domain/emoji/dao/EmojiDao.kt
=> fix: fix DownloadUrl

springboot/src/main/kotlin/com/goliath/emojihub/springboot/domain/post/controller/PostController.kt, springboot/src/main/kotlin/com/goliath/emojihub/springboot/domain/post/dao/PostDao.kt, springboot/src/main/kotlin/com/goliath/emojihub/springboot/domain/post/service/PostService.kt, springboot/src/test/kotlin/com/goliath/emojihub/springboot/domain/post/controller/PostControllerTest.kt, springboot/src/test/kotlin/com/goliath/emojihub/springboot/domain/post/dao/PostDaoTest.kt, springboot/src/test/kotlin/com/goliath/emojihub/springboot/domain/post/service/PostServiceTest.kt
Profile page에서 유저의 post를 db에서 불러오기 위한 api를 구현하였습니다
=> feat: feat getMyPosts API

android/app/src/main/java/com/goliath/emojihub/RootActivity.kt, android/app/src/main/java/com/goliath/emojihub/data_sources/SharedLocalStorage.kt, android/app/src/main/java/com/goliath/emojihub/usecases/UserUseCase.kt, android/app/src/main/java/com/goliath/emojihub/views/CreatePostPage.kt, android/app/src/main/java/com/goliath/emojihub/views/EmojiPage.kt, android/app/src/main/java/com/goliath/emojihub/views/FeedPage.kt, android/app/src/main/java/com/goliath/emojihub/views/LoginPage.kt, android/app/src/main/java/com/goliath/emojihub/views/components/PlayEmojiView.kt, android/app/src/main/java/com/goliath/emojihub/views/components/PostCell.kt
- 비회원모드일 시 포스트에 반응 추가, 포스트 작성, 이모지 생성, 이모지 저장을 할 수 없도록 Dialog를 추가하였습니다
- `User` 관련 상태가 업데이트될 때 `accessToken`만 갱신되고, `currentUser`는 갱신되지않아 발생했던 문제를 수정하였습니다
=> Add dialog for Non-User mode

android/app/src/main/java/com/goliath/emojihub/views/components/PlayEmojiView.kt
Unsave warning dialog에 "삭제" 버튼을 누르기 이전에 unsave toast가 뜨는 문제를 수정했습니다.
=> Fix unsave toast appears before confirm unsave warning dialog

android/app/src/main/java/com/goliath/emojihub/views/ProfilePage.kt
- 프로필탭에서 `저장한 이모지` 혹은 `내가 만든 이모지`에 대해 Cell 선택 시 `PlayEmojiView`로 navigate되도록 수정했습니다
=> Navigate to `PlayEmojiView` from `ProfileTab`

android/app/src/main/java/com/goliath/emojihub/views/components/CustomBottomSheet.kt
* 이모지를 업로드하자마자 포스트의 이모지가 업데이트되도록 수정했습니다.
* 불필요한 api call을 줄이기 위해 mySavedEmoji, myCreatedEmoji fetch call의 launched effect 조건을 분리했습니다
=> Fix 3 preview emoji update on uploading reaction

springboot/src/main/kotlin/com/goliath/emojihub/springboot/global/config/SecurityConfig.kt
- 리액션 목록을 받아올 때 accessToken이 없는 비회원 모드도 가능하도록 수정했습니다
=> Fetch reaction list for non-users

springboot/src/main/kotlin/com/goliath/emojihub/springboot/domain/emoji/service/EmojiService.kt
* 내가 저장한 이모지가 저장 시점의 역순(최신순)으로 정렬되도록 수정했습니다
=> Fix: sort saved emojis by descending order of saved time

.github/workflows/android.yaml, .github/workflows/springboot.yaml, android/app/build.gradle.kts, android/app/src/androidTest/java/com/goliath/emojihub/data_sources/local/MediaDataSourceImplTest.kt, android/app/src/androidTest/java/com/goliath/emojihub/data_sources/local/X3dDataSourceImplTest.kt, android/app/src/main/assets/zero_shot_classname_to_unicode.json, android/app/src/main/java/com/goliath/emojihub/data_sources/BuildConfig.kt, android/app/src/main/java/com/goliath/emojihub/data_sources/DataSourceModule.kt, android/app/src/main/java/com/goliath/emojihub/data_sources/NetworkModule.kt, android/app/src/main/java/com/goliath/emojihub/data_sources/api/ClipApi.kt, android/app/src/main/java/com/goliath/emojihub/data_sources/local/MediaDataSource.kt, android/app/src/main/java/com/goliath/emojihub/data_sources/local/X3dDataSource.kt, android/app/src/main/java/com/goliath/emojihub/models/Clip.kt, android/app/src/main/java/com/goliath/emojihub/models/responses/ClipInferenceResponse.kt, android/app/src/main/java/com/goliath/emojihub/repositories/RepositoryModule.kt, android/app/src/main/java/com/goliath/emojihub/repositories/local/X3dRepository.kt, android/app/src/main/java/com/goliath/emojihub/repositories/remote/ClipRepository.kt, android/app/src/main/java/com/goliath/emojihub/usecases/EmojiUseCase.kt, android/app/src/main/java/com/goliath/emojihub/viewmodels/EmojiViewModel.kt, android/app/src/main/java/com/goliath/emojihub/views/components/EmojiCell.kt, android/app/src/test/java/com/goliath/emojihub/repositories/local/X3dRepositoryImplTest.kt, android/app/src/test/java/com/goliath/emojihub/repositories/remote/ClipRepositoryImplTest.kt, android/app/src/test/java/com/goliath/emojihub/usecases/EmojiUseCaseImplTest.kt
*  Hugging face에서 제공하는 Inference API 를 연결하여 api request로 CLIP 모델에게 inference를 요청하는 코드를 작성하였습니다. Inference API는 테스트용 임시 api라 sagemaker를 통해 서버 구성 예정입니다. (Inference API는 최대 10개 class에 대한 분류만 가능)
* 관련해 ClipRepository, MediaDataSouce를 새로 만들었고, X3dRepository, X3dDataSource의 경우 리펙토링에 따른 수정이 있었습니다.
* inference를 위한 className -> unicode json 파일 만들기 (충분히 많은 class를 커버하도록)
* sagemaker 실시간 추론 서버 구축
=> Use CLIP model for video -> emoji inference

springboot/src/test/kotlin/com/goliath/emojihub/springboot/domain/emoji/dao/EmojiDaoTest.kt, springboot/src/test/kotlin/com/goliath/emojihub/springboot/domain/post/dao/PostDaoTest.kt, springboot/src/test/kotlin/com/goliath/emojihub/springboot/domain/reaction/dao/ReactionDaoTest.kt, springboot/src/test/kotlin/com/goliath/emojihub/springboot/domain/user/dao/UserDaoTest.kt
=> fix: fix test initialization
